/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MemberRouteImport } from './routes/member'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminExercisesRouteImport } from './routes/admin.exercises'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminMembershipsRouteImport } from './routes/admin.memberships'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminRegisterRouteImport } from './routes/admin.register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExercisesRoute = AdminExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/member': typeof MemberRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/member': typeof MemberRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/member': typeof MemberRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/member'
    | '/admin/attendance'
    | '/admin/exercises'
    | '/admin/members'
    | '/admin/memberships'
    | '/admin/payments'
    | '/admin/register'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/member'
    | '/admin/attendance'
    | '/admin/exercises'
    | '/admin/members'
    | '/admin/memberships'
    | '/admin/payments'
    | '/admin/register'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/member'
    | '/admin/attendance'
    | '/admin/exercises'
    | '/admin/members'
    | '/admin/memberships'
    | '/admin/payments'
    | '/admin/register'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MemberRoute: typeof MemberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exercises': {
      id: '/admin/exercises'
      path: '/exercises'
      fullPath: '/admin/exercises'
      preLoaderRoute: typeof AdminExercisesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminExercisesRoute: typeof AdminExercisesRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminMembershipsRoute: typeof AdminMembershipsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminExercisesRoute: AdminExercisesRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMembershipsRoute: AdminMembershipsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MemberRoute: MemberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
